import React, { useRef, useState } from "react";
import { FlatList, RefreshControl } from "react-native";
import { View, Text } from "react-native";
import { useInfiniteQuery, useQuery } from "react-query";
import ListItem from "./Listitem";
import FloatingButton from "./FloatingButton";
import Header from "./Community";
import TempTobBar from "./TempTobBar";
import ForumItem from "./ForumItem";

const GETCHA_API_URL =
  "https://dev-getcha-api.getcha.io/v7/community?page_per_count=30";
const HomeScreen = ({ index }) => {
  const [direction, setDirection] = useState("down");
  const axisY = useRef(0);
  console.log("Render at :", index);
  // const getCommunityList = {
  //   fetchAll: () =>
  //     fetch(`${GETCHA_API_URL}`).then((res) => {
  //       return res.json();
  //     }),
  //   fetchPagination: (page = 0) =>
  //     fetch(`${GETCHA_API_URL}&page=${page}`).then((res) => {
  //       return res.json();
  //     }),
  // };
  // const { isLoading, data } = useQuery("list", getCommunityList.fetchAll);
  // const { isLoading, data, fetchNextPage } = useInfiniteQuery(
  //   "lists",
  //   getCommunityList.fetchPagination,
  //   {
  //     getNextPageParam: (obj) => {
  //       if (obj.data.list.total_page_count > 0) {
  //         currentPage.current += 1;
  //         return currentPage.current;
  //       }
  //       return obj;
  //     },
  //   }
  // );
  const onScroll = (e) => {
    setDirection(axisY.current < e.nativeEvent.contentOffset.y ? "down" : "up");
    axisY.current = e.nativeEvent.contentOffset.y;
  };

  // if (isLoading) return <Text>isLoading</Text>;
  const renderItem = ({ item }) => {
    // return <ListItem item={item} />;
    return <Text>{item.id_contents}</Text>;
  };

  const onViewableItemsChanged = ({ viewableItems }) => {
    // if (lastItemInView.index > 30 * currentPage.current - 10) {
    //   fetchNextPage();
    //   currentPage.current += 1;
    // }
  };
  return (
    <View style={{ backgroundColor: "yellow" }}>
      <FlatList
        bounces={false}
        // data={data?.pages.map((d) => d.data.list.infos).flat()}
        data={dummy}
        renderItem={renderItem}
        // ListHeaderComponent={Header}
        showsVerticalScrollIndicator={false}
        // stickyHeaderIndices={[1]}
        keyboardShouldPersistTaps="always"
        keyExtractor={(item) => item.id_contents}
        // onViewableItemsChanged={onViewableItemsChanged}
        // viewabilityConfig={{
        //   waitForInteraction: true,
        //   viewAreaCoveragePercentThreshold: 95,
        // }}
        onScroll={onScroll}
        removeClippedSubviews
        contentContainerStyle={{ backgroundColor: "blue" }}
      />
      <FloatingButton direction={direction} />
    </View>
  );
};

export default HomeScreen;

const dummy = [
  {
    cell_type: "cell_community",
    type: 11,
    id_contents: 2033,
    view_cnt: 3,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337434,
    report_delete_yn: "N",
    created: "2022-03-14T05:52:10.000Z",
    display_date: "03.14",
    time_diff: 1617,
    type_name: "오너의 리뷰",
    title: "볼보 S90 B5 Inscription",
    nick_name: "데이빗 테스트",
    lv: 8,
    auth: "normal",
    rating: "3.0",
    image: [
      "https://cloud.getcha.io/file/11/image_upload/2022214/1647237093b3b45.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/2022214/1647237095TDHw4.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/2022214/1647237098vJH5I.jpeg",
    ],
    is_car_tag: "N",
    user_brand: [
      {
        image:
          "https://getcha.s3.ap-northeast-2.amazonaws.com/v7_brand_logo/brand_14_black/volvo.png",
        brand: "볼보",
      },
    ],
  },
  {
    cell_type: "cell_community",
    type: 11,
    id_contents: 2032,
    view_cnt: 2,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337374,
    report_delete_yn: "N",
    created: "2022-03-11T02:47:21.000Z",
    display_date: "03.11",
    time_diff: 6122,
    type_name: "오너의 리뷰",
    title: "벤틀리 Bentayga V8",
    nick_name: "로벝",
    lv: 18,
    auth: "normal",
    rating: "5.0",
    image: [
      "https://cloud.getcha.io/file/11/image_upload/2022211/1646966815iaLms.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/2022211/1646966818toERw.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/2022211/1646966821pUnDw.jpeg",
    ],
    is_car_tag: "N",
    user_brand: [
      {
        image:
          "https://getcha.s3.ap-northeast-2.amazonaws.com/v7_brand_logo/brand_14_black/bentley.png",
        brand: "벤틀리",
      },
      {
        image:
          "https://getcha.s3.ap-northeast-2.amazonaws.com/v7_brand_logo/brand_14_black/rollsroyce.png",
        brand: "롤스로이스",
      },
    ],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33417,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-10T23:52:58.000Z",
    display_date: "03.11",
    time_diff: 6297,
    type_name: "자유주제",
    title: "4월 24일 개막' 슈퍼레이스, 3년 만에 관중맞이",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33416,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-10T23:30:11.000Z",
    display_date: "03.11",
    time_diff: 6319,
    type_name: "자유주제",
    title: "정체불명' 노후 오토바이 단속…14만대 사용 폐지",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33415,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-10T07:49:33.000Z",
    display_date: "03.10",
    time_diff: 7260,
    type_name: "자유주제",
    title: "르노, 준중형 SUV 오스트랄 마침내 완전 공개!",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33413,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-10T00:18:21.000Z",
    display_date: "03.10",
    time_diff: 7711,
    type_name: "자유주제",
    title: "3시리즈도 PHEV' BMW 320e 출시…연비 15.8km/L·가격 5840만원",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33412,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-09T23:24:54.000Z",
    display_date: "03.10",
    time_diff: 7765,
    type_name: "자유주제",
    title: "서울시 전기차 보조금 '2개월에서 3개월'로 출고기한 연장",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 11,
    id_contents: 2031,
    view_cnt: 2,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337434,
    report_delete_yn: "N",
    created: "2022-03-08T09:12:20.000Z",
    display_date: "03.08",
    time_diff: 10057,
    type_name: "오너의 리뷰",
    title: "볼보 S90 T8 Inscription",
    nick_name: "데이빗 테스트",
    lv: 8,
    auth: "normal",
    rating: "3.5",
    image: [
      "https://cloud.getcha.io/file/11/image_upload/202228/1646730722KL3XQ.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/202228/1646730724uzckY.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/202228/1646730727FR6jA.jpeg",
    ],
    is_car_tag: "N",
    user_brand: [
      {
        image:
          "https://getcha.s3.ap-northeast-2.amazonaws.com/v7_brand_logo/brand_14_black/volvo.png",
        brand: "볼보",
      },
    ],
  },
  {
    cell_type: "cell_community",
    type: 11,
    id_contents: 2029,
    view_cnt: 1,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337434,
    report_delete_yn: "N",
    created: "2022-03-08T09:09:52.000Z",
    display_date: "03.08",
    time_diff: 10060,
    type_name: "오너의 리뷰",
    title: "볼보 S90 T8 Inscription",
    nick_name: "데이빗 테스트",
    lv: 8,
    auth: "normal",
    rating: "3.5",
    image: [
      "https://cloud.getcha.io/file/11/image_upload/202228/16467305670In8f.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/202228/1646730569NmBrQ.jpeg",
      "https://cloud.getcha.io/file/11/image_upload/202228/1646730571Efsie.jpeg",
    ],
    is_car_tag: "N",
    user_brand: [
      {
        image:
          "https://getcha.s3.ap-northeast-2.amazonaws.com/v7_brand_logo/brand_14_black/volvo.png",
        brand: "볼보",
      },
    ],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33414,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T08:43:20.000Z",
    display_date: "03.08",
    time_diff: 10086,
    type_name: "자유주제",
    title:
      '현대로템·현대제철 노조, "우리도 현대차·기아처럼 400만원 성과급 달라"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33407,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T06:34:29.000Z",
    display_date: "03.08",
    time_diff: 10215,
    type_name: "자유주제",
    title: '토요타 GR수프라, 수동변속기 추가된다…"출시 3년만"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33408,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T06:25:19.000Z",
    display_date: "03.08",
    time_diff: 10224,
    type_name: "자유주제",
    title: '한국GM 노조 "카젬 사장, 불법 파견 해결하고 떠나라"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33409,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T06:24:58.000Z",
    display_date: "03.08",
    time_diff: 10225,
    type_name: "자유주제",
    title: '어린이 통학차량 전기차 보급…서울시 "최대 1억4600만원 지원"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33410,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T06:04:36.000Z",
    display_date: "03.08",
    time_diff: 10245,
    type_name: "자유주제",
    title: '포스코케미칼-GM, "4900억 투입" 캐나다에 양극재 합작공장 설립',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33411,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T05:27:08.000Z",
    display_date: "03.08",
    time_diff: 10282,
    type_name: "자유주제",
    title: "현대차 아이오닉5, '영국 올해의 차' 선정",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33406,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T05:26:32.000Z",
    display_date: "03.08",
    time_diff: 10283,
    type_name: "자유주제",
    title: '폭스바겐, ID.버즈 인테리어 선공개…"가죽 대신 비건 소재 썼어요!"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33404,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T00:56:47.000Z",
    display_date: "03.08",
    time_diff: 10553,
    type_name: "자유주제",
    title: '정부, 비축유 442만 배럴 긴급 투입 "기름값 잡는다"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33405,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-08T00:47:31.000Z",
    display_date: "03.08",
    time_diff: 10562,
    type_name: "자유주제",
    title: "\"공급난 또 온다\"…러시아·우크라 전쟁에 자동차 산업 '경고음'",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33403,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T23:35:09.000Z",
    display_date: "03.08",
    time_diff: 10634,
    type_name: "자유주제",
    title: "현대차, 정숙성 강화한 '2022 아반떼' 출시…수동변속기 '단종'",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33402,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T09:23:34.000Z",
    display_date: "03.07",
    time_diff: 11486,
    type_name: "자유주제",
    title: "쏘카, SK 이어 롯데까지 1800억 '러브콜'…상장 초록불?",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33401,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T08:13:58.000Z",
    display_date: "03.07",
    time_diff: 11556,
    type_name: "자유주제",
    title: '"전동화부터 부품 공동구매까지" 현대차·이베코, 상용차 협업 추진',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33400,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T08:09:41.000Z",
    display_date: "03.07",
    time_diff: 11560,
    type_name: "자유주제",
    title: '검찰, 한국GM 카젬 사장에 세번째 출국정지…"불법파견 혐의"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33399,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T04:14:55.000Z",
    display_date: "03.07",
    time_diff: 11795,
    type_name: "자유주제",
    title:
      '현대차, 중고차 업계 상생안 제시 "5년·10만km 이하, 점유율 자체 제한"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33398,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T03:53:02.000Z",
    display_date: "03.07",
    time_diff: 11816,
    type_name: "자유주제",
    title: "스텔란티스, 올해 지프·푸조·DS 신차 9종 출시…시트로엥은 철수?",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33397,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T01:31:54.000Z",
    display_date: "03.07",
    time_diff: 11958,
    type_name: "자유주제",
    title: '[주간F1] "전쟁은 안 돼!" 러시아 드라이버도 계약 해지',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33394,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T00:57:21.000Z",
    display_date: "03.07",
    time_diff: 11992,
    type_name: "자유주제",
    title: '르노삼성 XM3, 연식변경 효과? "사전 계약만 2300대"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33395,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T00:52:17.000Z",
    display_date: "03.07",
    time_diff: 11997,
    type_name: "자유주제",
    title: '현대차, 중고차 시장 진출 공식 선언…"신차급 중고차 판매"',
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33393,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T00:09:20.000Z",
    display_date: "03.07",
    time_diff: 12040,
    type_name: "자유주제",
    title: "[이완 칼럼] 제네시스의 민망한 유럽 판매량…'전기차로 깃발 꽂아야'",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33396,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-07T00:07:20.000Z",
    display_date: "03.07",
    time_diff: 12042,
    type_name: "자유주제",
    title: "벤츠 신형 C클래스, 이달 출시…가격은 6150만원부터",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
  {
    cell_type: "cell_community",
    type: 13,
    id_contents: 33392,
    view_cnt: 0,
    reply_cnt: 0,
    like_cnt: 0,
    price: null,
    is_hot: "N",
    id_user: 337440,
    report_delete_yn: "N",
    created: "2022-03-06T23:30:36.000Z",
    display_date: "03.07",
    time_diff: 12079,
    type_name: "자유주제",
    title: "정부, 유류세 더 내린다…휘발유값 최대 305원 인하",
    notice: "N",
    nick_name: "모그 알리미",
    lv: 1,
    auth: "expert",
    image: [],
    is_car_tag: "N",
    user_brand: [],
  },
];
